--- a/build/Makefile.linux
+++ b/build/Makefile.linux
@@ -52,12 +52,10 @@
 
 clean:
 	rm -f $(OBJECTS) core $(EXECS) ; \
-	cp build/Makefile.w Makefile ; cd dns ; make clean ; \
+	cd dns ; make clean ; \
 	cd ../libs ; make clean ; cd ../parse ; make clean ; \
 	cd ../qual ; make clean ; \
 	cd ../server ; make clean ; \
-	cp Makefile.recursive Makefile ; \
-	cd ../test ; make clean ; \
 	cd ../tools ; make clean ; \
 	cd misc ; make clean ; \
 	cd ../../utf8 ; make clean ; \
--- a/server/Makefile
+++ b/server/Makefile
@@ -1,11 +1,13 @@
-SOBJECTS=MaraBigHash.o recursive.o timestamp.o read_kvars.o MaraAnyChain.o
+SOBJECTS=MaraBigHash.o recursive.o timestamp.o read_kvars.o MaraAnyChain.o \
+	udpsuccess.o
 JOBJS=../libs/JsStr.o ../libs/JsStrOS.o ../libs/JsStrCP.o 
 MHOBJS=../libs/MaraHash.o
 MJOBJS=../qual/qual_timestamp.o
+POBJ6=../parse/Csv2_rr_wks.o
 POBJ5=../parse/Csv2_database.o ../parse/Csv2_rr_txt.o ../parse/Csv2_esc_txt.o
 POBJ3=../parse/Csv2_rr_soa.o ../parse/Csv2_rr_aaaa.o ../parse/Csv2_rr_a.o
 POBJ2=../parse/Csv2_read.o ../parse/Csv2_main.o ../parse/Csv2_parse.o $(POBJ3)
-POBJ4=../parse/ParseIpAcl.o ../parse/Parse_ipv6.o $(POBJ2)
+POBJ4=../parse/ParseIpAcl.o ../parse/Parse_ipv6.o $(POBJ2) $(POBJ6)
 POBJECTS=../parse/ParseMaraRc.o ../parse/ParseCsv1.o $(POBJ4) $(POBJ5)
 DOBJECTS=../dns/Queries.o ../dns/Compress.o ../dns/bobbit.o ../dns/Decompress.o
 ROBJECTS=../rng/rng-api-fst.o ../rng/rng-alg-fst.o
@@ -46,6 +48,9 @@
 MaraAnyChain.o: MaraAnyChain.c
 	$(CC) -c $(FLAGS) -o MaraAnyChain.o MaraAnyChain.c
 
+udpsuccess.o: udpsuccess.c
+	$(CC) -c $(FLAGS) -o udpsuccess.o udpsuccess.c
+
 maradns: MaraDNS.c $(OBJECTS) MaraDNS_locale.h
 	$(CC) $(FLAGS) -DVERSION=\"$(VERSION)\" -DCOMPILED=\"$(COMPILED)\" -o maradns MaraDNS.c $(OBJECTS) -lpthread
 
--- a/qual/Makefile
+++ b/qual/Makefile
@@ -2,9 +2,6 @@
 JOBJS=../libs/JsStr.o ../libs/JsStrOS.o ../libs/JsStrCP.o 
 OBJECTS=$(DOBJECTS)
 
-#FLAGS = -g -Wall $(DEBUG)
-#FLAGS = -g $(DEBUG)
-
 all: qual_timestamp.o
 
 clean:
--- a/tcp/Makefile
+++ b/tcp/Makefile
@@ -2,10 +2,11 @@
 MJOBJS=../qual/qual_timestamp.o
 MHOBJS=../libs/MaraHash.o
 DOBJECTS=../dns/Queries.o ../dns/Compress.o ../dns/bobbit.o ../dns/Decompress.o
+POBJ6=../parse/Csv2_rr_wks.o
 POBJ5=../parse/Csv2_database.o ../parse/Csv2_rr_txt.o ../parse/Csv2_esc_txt.o
 POBJ3=../parse/Csv2_rr_soa.o ../parse/Csv2_rr_aaaa.o ../parse/Csv2_rr_a.o
 POBJ2=../parse/Csv2_read.o ../parse/Csv2_main.o ../parse/Csv2_parse.o $(POBJ3)
-POBJ4=../parse/ParseIpAcl.o ../parse/Parse_ipv6.o $(POBJ2)
+POBJ4=../parse/ParseIpAcl.o ../parse/Parse_ipv6.o $(POBJ2) $(POBJ6)
 POBJECTS=../parse/ParseMaraRc.o ../parse/ParseCsv1.o $(POBJ4) $(POBJ5)
 OBJECTS=../parse/ParseCsv1.o ../parse/ParseMaraRc.o ../parse/ParseIpAcl.o
 SOBJECTS=../server/timestamp.o ../server/MaraBigHash.o ../server/read_kvars.o \
@@ -16,7 +17,7 @@
 	$(TCPOBJS)
 EXECS=getzone zoneserver fetchzone
 
-FLAGS = -g -Wall $(DEBUG)
+#FLAGS = -g -Wall $(DEBUG)
 #FLAGS = -g $(DEBUG)
 
 all: $(EXECS)
--- a/dns/Makefile
+++ b/dns/Makefile
@@ -3,7 +3,7 @@
 MHOBJS=../libs/MaraHash.o
 OBJECTS=$(DOBJECTS) $(JOBJS) $(MHOBJS)
 
-FLAGS = -g -Wall $(DEBUG)
+#FLAGS = -g -Wall $(DEBUG)
 #FLAGS = -g $(DEBUG)
 
 all: Queries.o Compress.o bobbit.o Decompress.o
--- /dev/null
+++ b/tools/Makefile
@@ -0,0 +1,34 @@
+JOBJS=../libs/JsStr.o ../libs/JsStrOS.o ../libs/JsStrCP.o
+MHOBJS=../libs/MaraHash.o
+DOBJECTS=../dns/Queries.o ../dns/Compress.o ../dns/bobbit.o ../dns/Decompress.o
+SOBJECTS=../server/timestamp.o
+OUTOBJ=../parse/Csv2_esc_txt.o
+OBJECTS=$(JOBJS) $(MHOBJS) $(DOBJECTS) $(SOBJECTS)
+ROBJECTS=../rng/rng-alg-fst.o ../rng/rng-api-fst.o
+POBJECTS=../parse/ParseCsv1.o ../parse/ParseMaraRc.o
+Q=$(ROBJECTS) $(POBJECTS)
+EXECS=askmara askmara-tcp strip.control benchmark duende
+
+#FLAGS = -g $(DEBUG)
+#FLAGS = -g $(DEBUG)
+
+all: $(EXECS)
+
+clean:
+	rm -f core $(EXECS) *.exe
+
+askmara: askmara.c askmara_labels_en.h $(OBJECTS) $(Q) $(OUTOBJ)
+	$(CC) $(FLAGS) -o askmara askmara.c $(OBJECTS) $(Q) $(OUTOBJ)
+
+askmara-tcp: askmara-tcp.c askmara_labels_en.h $(OBJECTS) $(ROBJECTS) $(POBJECTS)
+	$(CC) $(FLAGS) -o askmara-tcp askmara-tcp.c $(OBJECTS) $(ROBJECTS) $(POBJECTS)
+
+benchmark: benchmark.c askmara_labels_en.h $(OBJECTS) $(POBJECTS)
+	$(CC) $(FLAGS) -o benchmark benchmark.c $(OBJECTS) $(POBJECTS)
+
+duende: duende.c
+	$(CC) $(FLAGS) -o duende duende.c
+
+strip.control: strip.control.c
+	$(CC) $(FLAGS) -o strip.control strip.control.c
+
