#!/bin/sh -e

set -e

if ! id -u maradns >/dev/null 2>&1 ; then

    echo "creating MaraDNS system user..."
    adduser --quiet --system --group --no-create-home --home /etc/maradns maradns

fi

mkdir -p /etc/maradns/logger

if [ "$1" = "configure" ] && [ -f $CFG_TEMPLATE ]
then
	IDNUM=`id -u maradns`
	GIDNUM=`id -g maradns`
        CFG_TEMPLATE=/usr/share/maradns/mararc
        CFG_TMP=/etc/maradns/mararc.dpkg-new
        CFG_FILE=/etc/maradns/mararc
	sed -e "s/^maradns_uid = .*$/maradns_uid = $IDNUM/" \
		-e "s/^# maradns_gid = .*$/maradns_gid = $GIDNUM/" < $CFG_TEMPLATE > $CFG_TMP
        ucf --debconf-ok $CFG_TMP $CFG_FILE && rm -f $CFG_TMP
fi

#DEBHELPER#

exit 0
