#!/bin/sh -e

set -e

case "$1" in

  purge)
    # See #621833. This behaviour is deprecated.
    # However there is no consensus on the correct implementation.
    # Also this might get missed because it does not use 'deluser'.
    userdel maradns ||true
    rm -rf /etc/maradns ||true
    ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    # do nothing
    ;;

  *)
    echo "$0: incorrect arguments: $*" >&2
    exit 1
    ;;

esac

#DEBHELPER#
