/* This file is automatically generated by RandomPrime */

/* Having the multiply constant hardcoded in the code makes things about
 * 8% faster; however, I want to make it a variable because then it
 * can easily be changed in one's dwood2rc file, allowing people to
 * protect themselves from "make a bunch of bogus queries that hash to
 * the same value" DOS attacks.  However, if you need that extra 8%
 * speed, uncomment the next line, but change the constant to some other
 * 32-bit prime number */
/*#define MUL_CONSTANT 1782541843 */
uint32_t magic_number = 1782541843;
/* 1782541843 has 18 bits set to 1 */
